### ISSUE TITLE
Copyright notice and license

### ISSUE THREAD

**Issue by masatake** [Perlence/ahktags#1]
I would like to use the regular expression patterns in ahnktags in [Universal-ctags](https://github.com/universal-ctags/ctags) to solve [the issue](https://github.com/universal-ctags/ctags/issues/2682).

However, there is no copyright notice and no license term in the source tree.
Could you write it explictly somewhere  in the source tree?
If POSIBLE, I would like you to choose "GPLv2 or later" or a license compatible with "GPLv2 or later" like https://github.com/universal-ctags/ctags/blob/master/optlib/pod.ctags .
So I can write a parser based on ahktags and put the parser in u-ctags.

**Comment by Perlence** [comment]
Hello @masatake, thank you for reaching out! I've added the 3-clause BSD license in the source tree.

**Comment by masatake** [comment]
Thank you.
